// <auto-generated />
using System;
using LogiSmart.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogiSmart.Api.Migrations
{
    [DbContext(typeof(MagazziniContext))]
    [Migration("20230216221308_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogiSmart.Api.Models.AreaMagazzino", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MagazzinoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroContatto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MagazzinoId");

                    b.ToTable("AreeMagazzino");
                });

            modelBuilder.Entity("LogiSmart.Api.Models.AttrezzaturaDiLavoro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<long?>("MansioneId")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeAttrezzatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MansioneId");

                    b.ToTable("AttrezzaturaDiLavoro");
                });

            modelBuilder.Entity("LogiSmart.Api.Models.Azienda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("CodiceUnivoco")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MagazzinoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroContatto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartitaIva")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Pec")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MagazzinoId");

                    b.ToTable("Aziende");
                });

            modelBuilder.Entity("LogiSmart.Api.Models.Magazzino", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Magazzini");
                });

            modelBuilder.Entity("LogiSmart.Api.Models.Mansione", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AreaMagazzinoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFinePrevisto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInizioPrevisto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MagazzinoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaMagazzinoId");

                    b.HasIndex("MagazzinoId");

                    b.ToTable("Mansioni");
                });

            modelBuilder.Entity("LogiSmart.Api.Models.Operatore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<long>("AziendaId")
                        .HasColumnType("bigint");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceOperatore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDiNascita")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndirizzoDiDomicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LuogoDiNascita")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MagazzinoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MansioneId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroContatto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sesso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AziendaId");

                    b.HasIndex("MagazzinoId");

                    b.HasIndex("MansioneId");

                    b.ToTable("Operatori");
                });

            modelBuilder.Entity("LogiSmart.Api.Models.AreaMagazzino", b =>
                {
                    b.HasOne("LogiSmart.Api.Models.Magazzino", "Magazzino")
                        .WithMany("AreaMagazzino")
                        .HasForeignKey("MagazzinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magazzino");
                });

            modelBuilder.Entity("LogiSmart.Api.Models.AttrezzaturaDiLavoro", b =>
                {
                    b.HasOne("LogiSmart.Api.Models.Mansione", "Mansione")
                        .WithMany("Attrezzature")
                        .HasForeignKey("MansioneId");

                    b.Navigation("Mansione");
                });

            modelBuilder.Entity("LogiSmart.Api.Models.Azienda", b =>
                {
                    b.HasOne("LogiSmart.Api.Models.Magazzino", "Magazzino")
                        .WithMany("Azienda")
                        .HasForeignKey("MagazzinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magazzino");
                });

            modelBuilder.Entity("LogiSmart.Api.Models.Mansione", b =>
                {
                    b.HasOne("LogiSmart.Api.Models.AreaMagazzino", "AreaMagazzino")
                        .WithMany("Mansioni")
                        .HasForeignKey("AreaMagazzinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogiSmart.Api.Models.Magazzino", null)
                        .WithMany("Mansioni")
                        .HasForeignKey("MagazzinoId");

                    b.Navigation("AreaMagazzino");
                });

            modelBuilder.Entity("LogiSmart.Api.Models.Operatore", b =>
                {
                    b.HasOne("LogiSmart.Api.Models.Azienda", "Azienda")
                        .WithMany()
                        .HasForeignKey("AziendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogiSmart.Api.Models.Magazzino", null)
                        .WithMany("Operatori")
                        .HasForeignKey("MagazzinoId");

                    b.HasOne("LogiSmart.Api.Models.Mansione", "Mansione")
                        .WithMany("Operatori")
                        .HasForeignKey("MansioneId");

                    b.Navigation("Azienda");

                    b.Navigation("Mansione");
                });

            modelBuilder.Entity("LogiSmart.Api.Models.AreaMagazzino", b =>
                {
                    b.Navigation("Mansioni");
                });

            modelBuilder.Entity("LogiSmart.Api.Models.Magazzino", b =>
                {
                    b.Navigation("AreaMagazzino");

                    b.Navigation("Azienda");

                    b.Navigation("Mansioni");

                    b.Navigation("Operatori");
                });

            modelBuilder.Entity("LogiSmart.Api.Models.Mansione", b =>
                {
                    b.Navigation("Attrezzature");

                    b.Navigation("Operatori");
                });
#pragma warning restore 612, 618
        }
    }
}
